### ISSUE TITLE
Fix de locale

### ISSUE THREAD

**Issue by philitell** [tomasweigenast/paged-datatable#11]
At the moment de-locale is not working because .arb-File is not properly configured
```
    "refreshedAtText": "Zuletzt aktualisiert um {time}",
    "@refreshedAtText": {
        "placeholders": {
            "Zeit": {}   <------------------ wrong placeholder should be "time"
        }
    },
```
I accidently renamed a placeholder - sorry my bad!

**Comment by philitell** [comment]
Thank you for all fixes - great work!!

**Comment by tomasweigenast** [comment]
My bad for not checking it before publishing! Thanks

**Comment by tomasweigenast** [comment]
@philitell you can start using the version that fixes this by using the dependency from github and the master branch. I want to release a new version with other fixes
