### ISSUE TITLE
Why this table has not the scrollbar for the horizontal view.

### ISSUE THREAD

**Issue by abdulrehman192** [tomasweigenast/paged-datatable#12]
If the columns length is more than the screen width then there is no horizontal scrollbar and it stretch the table and look of the table become ugly. Kindly add the horizontal scroll bar to the table on top on next previous strip. Thanks

**Comment by tomasweigenast** [comment]
The package was designed to have fixed width and relative column sizes. I will start developing a solution that includes a horizontal scrollbar, but it will take a while, because I don't know how to start and what to modify.

**Comment by tomasweigenast** [comment]
Good news. The first commit I made to the `horizontal-scroll` branch contains code to render cells larger than the viewport width and display a horizontal scroll. Hopefully in the next few days, I have a reproducible example

**Comment by blounsbury-usbr** [comment]
Hello. Just curious if this will get implemented soon.

**Comment by tomasweigenast** [comment]
> Hello. Just curious if this will get implemented soon.

Check the v2 dev at pub.dev
