### ISSUE TITLE
Bug when I remove two rows consecutively

### ISSUE THREAD

**Issue by wistian1996** [tomasweigenast/paged-datatable#15]
Olá, aparentemente quando eu chamo a função "tableController.removeRow", funciona perfeitamente na primeira chamada, mas na segunda vez, a tabela fica confusa e não remove a linha correta.

**Comment by tomasweigenast** [comment]
Can you describe the problem better? What happens when you call twice `tableController.removeRemove`?

**Comment by wistian1996** [comment]
Sorry for not describing the problem better.

https://github.com/tomasweigenast/paged-datatable/assets/23040335/7c9cc20e-514c-4fa2-af47-b850affbaabf

look, when removing a row, works on the first time, the second time the indexing seems to be incorrect

**Comment by tomasweigenast** [comment]
Please try the new pre-release version @wistian1996
