### ISSUE TITLE
Invalid state handling

### ISSUE THREAD

**Issue by Zekfad** [tomasweigenast/paged-datatable#17]
In your library you're linking state against controller which is incorrect (state should be created and managed by controller):

https://github.com/tomasweigenast/paged-datatable/blob/240139f9cd20a4446d2835a522be52bf31cc723c/lib/src/paged_datatable_state.dart#L297

If you create controller and dispose it before state is linked (e.g. conditional table rendering) late initialization error will be thrown.

To reproduce:
```dart
PagedDataTableController()..dispose();
```

**Comment by tomasweigenast** [comment]
This is the old version. Please check the new pre-release version: https://pub.dev/packages/paged_datatable/versions/2.0.0-dev.4

**Comment by Zekfad** [comment]
Thank you for the quick response, will check it!
