### ISSUE TITLE
Update to intl 0.19.0

### ISSUE THREAD

**Issue by philitell** [tomasweigenast/paged-datatable#19]
With Flutter 3.22 - flutter_localizations depends on intl 0.19 - please update paged-datatable to intl 0.19

**Comment by philitell** [comment]
thanks for this great project

**Comment by tomasweigenast** [comment]
Hello @philitell. Thanks for reporting that. I was waiting for `flutter_localizations` to be updated to  `intl` 0.19 before creating a release on pub.
