### ISSUE TITLE
how to remove footer buttons

### ISSUE THREAD

**Issue by heshesh2010** [tomasweigenast/paged-datatable#2]
Hi , thanks for this package , 

I just want to use my footer widget in all the bottom space not just the left side , so I want to remove your own footer widget and use my new footer instead

**Comment by tomasweigenast** [comment]
Hi! Thanks for using my package.

Its not supported at this moment, but give me a second and I will add it  😃

**Comment by tomasweigenast** [comment]
Close because of #3
