### ISSUE TITLE
Seems the widget is not updated when orderby changes

### ISSUE THREAD

**Issue by LAMXkE** [tomasweigenast/paged-datatable#21]
Hi 

I'm trying to sort List by using sortable: true option of TableColumn

And it seems the widget is showing previous datas.

I have to manually press refresh button to update my rows.

Your demo page seems to have a same problem. sorting by Gender column does not work at all until pressing refresh.

**Comment by LAMXkE** [comment]
I've figured out that in controller.dart:390 is the main problem 

If I comment  the whole block below  and put 
```
_currentDataset.clear();
_currentDataset.addAll(items);
```

it seems to be working.

**Comment by tomasweigenast** [comment]
> I've figured out that in controller.dart:390 is the main problem
> 
> If I comment the whole block below and put
> 
> ```
> _currentDataset.clear();
> _currentDataset.addAll(items);
> ```
> 
> it seems to be working.

Did you remove the *else if* statements too?

**Comment by tomasweigenast** [comment]
Closed as fixed in 2.0.1
