### ISSUE TITLE
Table does not use full width

### ISSUE THREAD

**Issue by philitell** [tomasweigenast/paged-datatable#26]
I'm trying to migrate from version 1.4.3 to 2.1 in a flutter web-project but i'm not able to achieve same results.
I'm using 10 TableColumns and it seems that the table does not use all available space (with and without specified sizes). When i use FractionalColumnSizes (where all values sum up to 1) one column seems to disappear. Furthermore, when i resize the table, no horizontal scroll bar is shown.

Result from version 2.1
![Bildschirmfoto vom 2024-06-11 09-33-55](https://github.com/tomasweigenast/paged-datatable/assets/87064261/9fa25260-8cbd-414f-a698-83a56b241f15)

Result from version 1.4.3
![Bildschirmfoto vom 2024-06-11 09-34-20](https://github.com/tomasweigenast/paged-datatable/assets/87064261/13e8fc44-a6ee-4081-95e8-0c696ab54889)

**Comment by philitell** [comment]
Here is a reproducible example: "table_test_page.dart" in https://github.com/philitell/paged_data_table_test

**Comment by philitell** [comment]
Do you have any tips for me how to solve this issue?

**Comment by tomasweigenast** [comment]
I think the problem is because you use `FractionalColumnSize(.1)` in every column. Applying `RemainingColumnSize` to the last column solves the issue (I tested it in your code).
I will keep this open because I don't know if we should consider this as an issue or not

**Comment by philitell** [comment]
Thank you very much!!

**Comment by costanzaminarelli** [comment]
This fix doesn't make sense. If FractionalColumnSize is a percentage value, and I have 10 columns each with FractionalColumnSize(.1), I expect each column to occupy 10% of the available space. However, this doesn't happen, and I end up with unused white space at the end of the table.

**Comment by tomasweigenast** [comment]
Yes, that is why I kept this issue open. I will continue working to fix it

**Comment by tomasweigenast** [comment]
Fixed!
