### ISSUE TITLE
How to make a Collapsible row

### ISSUE THREAD

**Issue by itsfahiz** [tomasweigenast/paged-datatable#33]
https://github.com/user-attachments/assets/91e8b9af-f389-49ff-9019-a37cb6833561
![Screenshot 2024-08-07 at 11 59 43 AM](https://github.com/user-attachments/assets/350ff815-d60f-4b86-b5d8-da428ec0d364)
![Screenshot 2024-08-07 at 11 59 58 AM](https://github.com/user-attachments/assets/62cea6d6-2781-4291-87d8-fe5adab17258)

How create a collapsible row as per the video and photo's. 
**High priority issue. please let me know the solution.**
Thank you

**Comment by tomasweigenast** [comment]
Hello. It is not possible right now. I can start developing a solution because its a good feature, but currently it not possible.

**Comment by itsfahiz** [comment]
Hey, Thank you for the update. I appreciate your willingness to develop a solution for the collapsible row feature.

We currently depend on this package for our project, and having this feature would be incredibly beneficial. If it becomes available soon, it would be fantastic and would greatly enhance our project and will be really helpful for others too. 
I also want to mention that all other features of the package are excellent and have been very valuable to us.

Looking forward to your solution.
Thank you

**Comment by tomasweigenast** [comment]
I'll start writing code asap. I don't guarantee you nothing but maybe for the next week it will be available as a preview

**Comment by itsfahiz** [comment]
Hi Tomas,

Thank you very much for your prompt response and for beginning work on the collapsible row feature. I sincerely appreciate your efforts and dedication to improving the package.

While I understand that nothing is guaranteed, having a preview by next week would be greatly appreciated and would be a wonderful addition to our project.

If there’s any way I can support you in this process or if you need any additional information, please feel free to let me know. May your work be blessed with success.

Thank you once again for your help.

**Comment by itsfahiz** [comment]
Hey Thomas, Have any updates?

**Comment by tomasweigenast** [comment]
Working on this

**Comment by itsfahiz** [comment]
Thanks!

**Comment by tomasweigenast** [comment]
@itsfahiz if you configure the `paged_datatable` dep in pubspec.yaml to use the **feat/expandable-rows** branch you can test the feature. It is incomplete and there is a lot to improve and document, but you can play around with that. If you want to implement collapsible/expansible rows, you have to use the `PagedDataTable.expansible` constructor and update the `fetcher`.

**Comment by tomasweigenast** [comment]
I am going to close this because the feature is already implemented in `dev` branch. I am creating a pre-release later on pub.dev.
