### ISSUE TITLE
overflow error occurs when there are more than 10 columns

### ISSUE THREAD

**Issue by bymoye** [tomasweigenast/paged-datatable#34]
As long as there are more than 10 items in Columns, "Total fraction exceeds 1.0, which means the columns will overflow." will appear. I think the expectation is to scroll to the right instead of directly prompting overflow, perhaps related to #29

**Comment by tomasweigenast** [comment]
You must use `RemainingColumnSize` in one or more columns to allow scrolling to the right. At least you have to place that in the last column.

**EDIT:** What you can do also is to set a fixed width to some of the columns but you can't use fractional column size that exceeds 1.0, it is not possible to calculate dynamic widths in LayoutBuilder when the width is not known until layout.

**Comment by bymoye** [comment]
> You must use `RemainingColumnSize` in one or more columns to allow scrolling to the right. At least you have to place that in the last column.
> 
> **EDIT:** What you can do also is to set a fixed width to some of the columns but you can't use fractional column size that exceeds 1.0, it is not possible to calculate dynamic widths in LayoutBuilder when the width is not known until layout.

I mean, the default size is const `FractionalColumnSize(0.1)`, in this case if there are more than 10 items in columns, then there will be a problem of >1.0.
Maybe it is necessary to state in the document that more than 10 items need to manually set the size?

**Comment by tomasweigenast** [comment]
I agree with you. I'm going to close this and probably change the default column size in the next release (or completely remove the default value, forcing you to set the size.)
