### ISSUE TITLE
Integrate with FirestoreQueryBuilder

### ISSUE THREAD

**Issue by degloff** [tomasweigenast/paged-datatable#44]
It would be helpful to have FirestoreQueryBuilder integrated or a sample using StreamBuilder.

**Comment by tomasweigenast** [comment]
Hello. Can you explain why it should be integrated?

**Comment by degloff** [comment]
Actually I wrote a quick adapter using the Firestore API to create the dataset with pagination. Works easier than I thought. Pagination in Firestore has its limitations, in particular with realtime updates happing while a user browses through the data. We can close it.
