### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by Somtobro** [tomasweigenast/paged-datatable#7]
Hey there, I built the example app to my Android device and it didn't look well.
I've attached a screenshot. This package has a lot of potential though the idea of it being built from scratch and rendering on demand is brilliant.
I would love to see a working example project
![Screenshot_20230906_114336](https://github.com/tomasweigenast/paged-datatable/assets/93442799/b0a2c8ec-2403-43bd-834f-f8e737ebd560)

**Comment by Somtobro** [comment]
Oh...I see, thanks anyways.
When this is ready for mobile, I can bet flutter is going to write you to purchase the package cos the idea is brilliant, can't wait!

**Comment by tomasweigenast** [comment]
I will keep this opened in case we can discuss about how to do a good mobile implementation

**Comment by Somtobro** [comment]
When does the discussion start?

**Comment by abhimuktheeswarar** [comment]
In the same app (hosted online). I'm able to click a row. i.e the cursor changes to a hand symbol when hovering over a row.
But, I'm not able to find a way to enable or add a clickable to row.

**Comment by tomasweigenast** [comment]
@abhimuktheeswarar can you create a separated issue for what you are describing?

**Comment by abhimuktheeswarar** [comment]
Kindly check this:
@tomasweigenast https://github.com/tomasweigenast/paged-datatable/issues/13

**Comment by Somtobro** [comment]
What's the update on this?
Has it been made to look nice on mobile?

**Comment by Amein-Eskinder** [comment]
Yes @tomasweigenast  for me as welll I have been looking for a work around so that in smaller client's would be able to scroll horizontally to see the last column?
